version: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce-git
    auth:
      username: ${DOCKERHUB_USER}
      password: ${DOCKERHUB_TOKEN}
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker buildx build --help
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin          
            docker buildx build --push \
              -f DockerfileCore \
              --build-arg BASE_IMAGE=python:3.9.2-slim --build-arg DAGSTER_VERSION=1.1.6 \
              --platform linux/amd64,linux/arm64 \
              -t ${DOCKERHUB_USER}/dagster:test .
      - run:
          name: Push Docker image
          command: |
            docker login --help
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: build_image
